---
title: "Project2"
author: "Yuzhi Li, Katelyn Settlemyre"
date: "2022-10-03"
output: 
  html_document:
    toc: TRUE
    toc_depth: 2
---

```{r packages, include=FALSE}
#packages needed to get API data and work with it
library(httr)
library(jsonlite)
library(tidyverse)
```


# Example of R-code that can contact Food data API by searching criteria

```{r}
res<-GET("https://api.spoonacular.com/recipes/complexSearch?query=chicken&maxFat=60&number=5&apiKey=be3c2a74ce6c4f0c83b254b34ceca7f5")
```

# Requirements





# API Interaction Functions

```{r}
recipe.search<- function(key=NULL, query=NULL, diet=NULL, type=NULL, maxCarbs=NULL, minProtein=NULL, maxFat=NULL){
  if(is.null(key)){
    return("your API Key is required.")
  }
  basic.url<-"https://api.spoonacular.com/recipes/complexSearch"
  data<-httr::GET(paste0(basic.url, "?query=", query, "&diet=", diet, "&type=", type, "&maxCarbs=", maxCarbs, "&minProtein=", minProtein, "&maxFat=", maxFat, "&apiKey=", key))
  
    mydf<- jsonlite::fromJSON(data$url)
    if(is.data.frame(mydf)== FALSE){
      return("No results")
    } else {
      return(mydf)
    }
  }
```



# Data Exploration





# Wrap-Up